apiVersion: v1
kind: ConfigMap
metadata: 
  name: i27-helpdesk-gateway-cm
  namespace: ${NAMESPACE}
data:
  SERVER_PORT: "8080"
  UI_ORIGIN: "http://34.86.231.101:32320"
  # UI_ORIGIN: "34.86.168.219:32320"
  # UI_ORIGIN: "dev.i27helpdesk.in"
  #AUTH_SERVICE_URL: "34.86.232.187:8081"
  # Service DNS names: http://<service-name>.<namespace>.svc.cluster.local
  AUTH_SERVICE_URL: "http:///i27-helpdesk-auth.${NAMESPACE}.svc.cluster.local"
  TICKET_SERVICE_URL: "http://i27-helpdesk-ticket.${NAMESPACE}.svc.cluster.local"
  COMMENT_SERVICE_URL: "http://i27-helpdesk-comment.${NAMESPACE}.svc.cluster.local"
  ATTACHMENT_SERVICE_URL: "http://i27-helpdesk-attachment.${NAMESPACE}.svc.cluster.local"


# http://34.86.232.187:32320/